### ISSUE TITLE
When observatory repos are created from the gdocs, a README needs to be added automatically as well

### ISSUE THREAD

**Issue by kmexter** [emo-bon/emobon-dm-tools#6]
Content of the README should be something like this
"Here you find the content of the EMO BON logsheets, which are harvested from the google doc for this observatory into [downloads/gdoc-csv](https://github.com/emo-bon/REPONAME/tree/main/downloads/gdoc-csv).

Last harvest: DATE

**Comment by bulricht** [comment]
READMEs are in place, I'll update the contents as well
